import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import JSZip from 'jszip'
import { jsPDF } from 'jspdf'

async function acceptBoundary(page: import('@playwright/test').Page) {
  await page.goto('/')
  const begin = page.getByRole('button', { name: 'Begin safety check' })
  await expect(begin).toBeDisabled()
  await page.getByLabel(/I understand Aduen's role/).check()
  await begin.click()
}

async function reachCaseDetails(page: import('@playwright/test').Page) {
  await acceptBoundary(page)
  await page.getByRole('button', { name: /No urgent issue/ }).click()
  await expect(page.getByRole('heading', { name: 'Describe the purchase.' })).toBeVisible()
}

async function fillCase(page: import('@playwright/test').Page, overrides: { purpose?: string; category?: string; consumerLocation?: string } = {}) {
  await page.getByLabel('Your name or chosen case name').fill('Synthetic Test Consumer')
  await page.getByLabel('Your location').selectOption(overrides.consumerLocation ?? 'malaysia')
  await page.getByLabel('Seller or merchant').fill('Synthetic Store')
  await page.getByLabel('Seller location').selectOption('malaysia')
  await page.getByLabel('Purchase date').fill('2026-08-01')
  await page.getByLabel('Amount paid (MYR)').fill('125.50')
  await page.getByLabel('Payment method').selectOption({ label: 'Card' })
  await page.getByLabel('Purchase purpose').selectOption(overrides.purpose ?? 'personal')
  await page.getByLabel('Purchase category').selectOption(overrides.category ?? 'general_goods')
  await page.getByLabel('What went wrong?').selectOption('non_delivery')
  await page.getByLabel('Primary remedy').selectOption('refund')
  await page.getByLabel('Refund amount (RM)').fill('125.50')
  await page.getByLabel('Merchant contact').selectOption('none')
  await page.getByRole('button', { name: /Save case draft/ }).click()
}

async function addEvidence(page: import('@playwright/test').Page, type: string, name: string, description: string) {
  await page.getByLabel('Original file').setInputFiles({ name, mimeType: 'text/plain', buffer: Buffer.from(`Synthetic ${description}. No real consumer information.`) })
  await page.getByLabel('What kind of record?').selectOption(type)
  await page.getByLabel('Event date').fill('2026-08-01')
  await page.getByLabel('Description').fill(description)
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await expect(page.getByText(name)).toBeVisible()
}

test('uncertain scope prevents pack preparation even with complete evidence', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page, { category: 'other' })
  await page.getByRole('button', { name: /Add evidence/ }).click()
  await addEvidence(page, 'receipt', 'receipt.txt', 'order receipt')
  await addEvidence(page, 'payment', 'payment.txt', 'payment record')
  await addEvidence(page, 'listing', 'listing.txt', 'delivery promise')
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByText('0', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Manual scope review' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Manual review needed' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Prepare merchant request' })).toHaveCount(0)
})

test('urgent risk blocks the ordinary intake path', async ({ page }) => {
  await acceptBoundary(page)
  await page.getByLabel('A payment or transaction was not authorised by me').check()
  await expect(page.getByRole('alert')).toContainText('Pause ordinary case preparation')
  await expect(page.getByRole('button', { name: /No urgent issue/ })).toHaveCount(0)
})

test('uploaded images can be previewed and closed locally', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  const originalPng = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=', 'base64')
  await page.getByLabel('Original file').setInputFiles({ name: 'synthetic-pixel.png', mimeType: 'image/png', buffer: originalPng })
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await page.getByLabel('I reviewed these warnings and still need to include this original.').check()
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await page.getByRole('button', { name: 'Preview image', exact: true }).click()
  const preview = page.getByRole('img', { name: 'synthetic-pixel.png' })
  await expect(preview).toBeVisible()
  await expect.poll(() => preview.evaluate((image: HTMLImageElement) => image.naturalWidth)).toBe(1)
  await expect(preview).toHaveAttribute('src', /^blob:/)
  await page.getByRole('button', { name: 'Prepare redacted image copy' }).click()
  const imageBox = await preview.boundingBox()
  expect(imageBox).not.toBeNull()
  await page.mouse.move(imageBox!.x + 0.1, imageBox!.y + 0.1)
  await page.mouse.down()
  await page.mouse.move(imageBox!.x + Math.max(0.9, imageBox!.width - 0.1), imageBox!.y + Math.max(0.9, imageBox!.height - 0.1))
  await page.mouse.up()
  const redactedDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download redacted image copy' }).click()
  const redactedFile = await redactedDownload
  expect(redactedFile.suggestedFilename()).toBe('redacted-synthetic-pixel.png')
  expect(Buffer.compare(await readFile((await redactedFile.path())!), originalPng)).not.toBe(0)
  await page.getByRole('button', { name: 'Clear redactions' }).click()
  await page.getByRole('button', { name: 'Add central redaction' }).click()
  const keyboardRedactedDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download redacted image copy' }).click()
  expect((await keyboardRedactedDownload).suggestedFilename()).toBe('redacted-synthetic-pixel.png')
  await page.getByRole('button', { name: 'Close image preview' }).click()
  await expect(preview).toHaveCount(0)
  const originalDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download original' }).click()
  const originalFile = await originalDownload
  expect(originalFile.suggestedFilename()).toBe('synthetic-pixel.png')
  expect(await readFile((await originalFile.path())!)).toEqual(originalPng)
})

test('uploaded PDFs can be redacted locally into a flattened copy without changing the original', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  const fixture = new jsPDF({ unit: 'pt', format: [600, 800] })
  fixture.setFontSize(24)
  fixture.text('SYNTHETIC PRIVATE DETAILS', 90, 130)
  const originalBytes = Buffer.from(fixture.output('arraybuffer'))
  await page.getByLabel('Original file').setInputFiles({ name: 'synthetic-receipt.pdf', mimeType: 'application/pdf', buffer: originalBytes })
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await page.getByLabel('I reviewed these warnings and still need to include this original.').check()
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await page.getByRole('button', { name: 'Preview and redact PDF', exact: true }).click()
  const exportButton = page.getByRole('button', { name: 'Download flattened redacted PDF' })
  await expect(exportButton).toBeDisabled()
  const pdfPage = page.locator('section[aria-label="Page 1"]')
  await expect(pdfPage.locator('canvas')).toBeVisible()
  await expect(page.getByRole('status', { name: 'Rendering PDF pages…' })).toHaveCount(0)
  await expect(exportButton).toBeDisabled()
  await pdfPage.locator('canvas').evaluate((canvas) => window.scrollBy(0, canvas.getBoundingClientRect().top - 100))
  const canvasBox = await pdfPage.locator('canvas').boundingBox()
  expect(canvasBox).not.toBeNull()
  await page.mouse.move(canvasBox!.x + canvasBox!.width * 0.12, canvasBox!.y + canvasBox!.height * 0.11)
  await page.mouse.down()
  await page.mouse.move(canvasBox!.x + canvasBox!.width * 0.65, canvasBox!.y + canvasBox!.height * 0.17)
  await page.mouse.up()
  await expect(exportButton).toBeEnabled()
  const redactedDownload = page.waitForEvent('download')
  await exportButton.click()
  const redactedFile = await redactedDownload
  expect(redactedFile.suggestedFilename()).toMatch(/^redacted-evidence-.+\.pdf$/)
  const redactedBytes = await readFile((await redactedFile.path())!)
  expect(redactedBytes.subarray(0, 5).toString()).toBe('%PDF-')
  expect(redactedBytes.includes(Buffer.from('SYNTHETIC PRIVATE DETAILS'))).toBe(false)

  const originalDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download original' }).click()
  const original = await originalDownload
  expect(await readFile((await original.path())!)).toEqual(originalBytes)
})

test('draft deletion can be cancelled and confirmed deletion removes saved case data', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  page.once('dialog', (dialog) => dialog.dismiss())
  await page.getByRole('button', { name: 'Delete draft', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Delete draft', exact: true })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('Aduen.case-record.v1'))).not.toBeNull()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete draft', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Begin safety check' })).toBeDisabled()
  expect(await page.evaluate(() => localStorage.getItem('Aduen.case-record.v1'))).toBeNull()
  expect(await page.evaluate(() => localStorage.getItem('Aduen.audit-log.v1'))).toBeNull()
  await page.reload()
  await expect(page.getByRole('button', { name: /Resume saved case/ })).toHaveCount(0)
})

test('an unsupported sector stops before evidence collection', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page, { category: 'healthcare' })
  await expect(page.getByRole('heading', { name: 'Aduen should not prepare this case.' })).toBeVisible()
  await expect(page.getByText('Healthcare matters are excluded')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add evidence' })).toHaveCount(0)
})

test('aviation cases receive the current CAAM handoff before evidence collection', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page, { category: 'aviation' })
  await expect(page.getByRole('heading', { name: 'Aduen should not prepare this case.' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Open CAAM/FlySmart complaint guidance' })).toHaveAttribute('href', 'https://www.caam.gov.my/consumer/complaints/make-a-complaint/')
  await expect(page.getByText('Contact the airline, airport, or provider first.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add evidence' })).toHaveCount(0)
})

test('financial-service cases receive the provider-first BNM handoff before evidence collection', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page, { category: 'financial_service' })
  await expect(page.getByRole('link', { name: 'Open Bank Negara Malaysia complaint process' })).toHaveAttribute('href', 'https://www.bnm.gov.my/contact-us/lodge-complaint')
  await expect(page.getByText('Complain to the financial service provider’s Complaints Unit first.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add evidence' })).toHaveCount(0)
})

test('a supported draft preserves original evidence and resumes at the evidence stage', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  await page.getByLabel('Original file').setInputFiles({ name: 'synthetic-receipt.txt', mimeType: 'text/plain', buffer: Buffer.from("Synthetic order receipt. Total MYR 125.50. This contains someone else's phone number. <script>window.evidenceExecuted=true</script>") })
  await page.getByLabel('Event date').fill('2026-08-01')
  await page.getByLabel('Description').fill('Synthetic order receipt')
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await expect(page.getByRole('alert')).toContainText('appears to mention another person')
  await page.getByLabel('I reviewed these warnings and still need to include this original.').check()
  await page.getByRole('button', { name: 'Add evidence' }).click()
  const inclusion = page.getByLabel('Include in pack')
  await inclusion.click()
  await expect(inclusion).not.toBeChecked()
  await inclusion.click()
  await expect(inclusion).toBeChecked()
  await expect(page.getByText('synthetic-receipt.txt')).toBeVisible()
  await page.getByRole('button', { name: 'Preview text', exact: true }).click()
  await expect(page.getByLabel('Evidence contents')).toContainText('<script>window.evidenceExecuted=true</script>')
  expect(await page.evaluate(() => 'evidenceExecuted' in window)).toBe(false)
  await page.getByRole('button', { name: 'Prepare redacted copy' }).click()
  const redactedCopy = page.getByLabel('Redacted copy contents')
  await expect(redactedCopy).toBeVisible()
  await redactedCopy.fill('Synthetic order receipt. [redacted]')
  const redactedDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download redacted copy' }).click()
  const redactedFile = await redactedDownload
  expect(redactedFile.suggestedFilename()).toMatch(/^redacted-evidence-.+\.txt$/)
  const redactedContent = await readFile((await redactedFile.path())!, 'utf8')
  expect(redactedContent).toContain('[redacted]')
  expect(redactedContent).not.toContain('window.evidenceExecuted')
  await page.getByRole('button', { name: 'Close redacted copy' }).click()
  await page.getByRole('button', { name: 'Close text preview' }).click()
  await expect(page.getByLabel('Evidence contents')).toHaveCount(0)
  const originalDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download original' }).click()
  const originalFile = await originalDownload
  expect(originalFile.suggestedFilename()).toBe('synthetic-receipt.txt')
  expect(await readFile((await originalFile.path())!, 'utf8')).toContain('window.evidenceExecuted')
  await page.reload()
  await page.getByRole('button', { name: /Resume saved case/ }).click()
  await expect(page.getByRole('heading', { name: 'Keep the originals.' })).toBeVisible()
  await expect(page.getByText('synthetic-receipt.txt')).toBeVisible()
  await page.getByRole('button', { name: 'Data controls' }).click()
  await expect(page.getByRole('heading', { name: 'Local activity history' })).toBeVisible()
  await page.getByText(/View \d+ recorded actions?/).click()
  await expect(page.getByText('Case edited', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Evidence inclusion changed', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Evidence previewed')).toBeVisible()
})

test('a complete merchant-first case reaches approved PDF export and outcome tracking', async ({ page }) => {
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  await addEvidence(page, 'receipt', 'receipt.txt', 'order receipt')
  await addEvidence(page, 'payment', 'payment.txt', 'payment record')
  await addEvidence(page, 'listing', 'listing.txt', 'promised delivery listing')
  await addEvidence(page, 'message', 'message.txt', 'written merchant request')
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByText('0', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Merchant or platform first' })).toBeVisible()
  await page.getByRole('button', { name: 'Prepare merchant request' }).click()
  await expect(page.getByText('Aduen CASE PACK')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Export PDF and selected evidence (ZIP)' })).toBeDisabled()
  await page.getByLabel(/I reviewed this pack/).check()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: /Approve and export PDF/ }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('Aduen-synthetic-store-v1.pdf')
  await page.getByRole('button', { name: 'Copy approved request' }).click()
  await expect(page.getByRole('button', { name: 'Request copied' })).toBeVisible()
  const archivePromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export PDF and selected evidence (ZIP)' }).click()
  const archiveDownload = await archivePromise
  expect(archiveDownload.suggestedFilename()).toBe('Aduen-synthetic-store-v1-handoff.zip')
  const archive = await JSZip.loadAsync(await readFile((await archiveDownload.path())!))
  const manifest = JSON.parse(await archive.file('manifest.json')!.async('string'))
  expect(manifest.evidence).toHaveLength(4)
  for (const entry of manifest.evidence) {
    expect(await archive.file(entry.archivePath)!.async('string')).toContain('Synthetic')
  }
  expect(await archive.file('Aduen-synthetic-store-v1.pdf')!.async('string')).toMatch(/^%PDF/)
  await page.getByRole('button', { name: /Track external status/ }).click()
  await page.getByLabel('Recipient or channel').fill('Synthetic merchant email')
  await page.getByLabel('Submission date').fill('2026-08-10')
  await page.getByLabel('External reference').fill('SYNTH-001')
  await page.getByLabel('Next follow-up').fill('2026-08-17')
  await page.getByLabel('Response summary').fill('Synthetic merchant acknowledged the request.')
  await page.getByRole('button', { name: /Save status/ }).click()
  await expect(page.getByRole('status')).toContainText('Status saved')
  await expect(page.getByText('Awaiting response', { exact: true })).toBeVisible()
  await expect(page.getByText('This reminder is based on the follow-up date you entered, not an external deadline.')).toBeVisible()
  const calendarDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download calendar reminder' }).click()
  expect((await calendarDownload).suggestedFilename()).toBe('Aduen-follow-up-2026-08-17.ics')
  await page.reload()
  await page.getByRole('button', { name: /Resume saved case/ }).click()
  await expect(page.getByLabel('External reference')).toHaveValue('SYNTH-001')
  await page.getByRole('button', { name: '← Pack', exact: true }).click()
  await expect(page.getByText('Aduen CASE PACK')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Export PDF and selected evidence (ZIP)' })).toBeEnabled()
  await page.getByRole('button', { name: '← Aduen Check', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Review the record.' })).toBeVisible()
  await expect(page.getByText('0', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Prepare merchant request' })).toBeEnabled()
  await page.getByRole('button', { name: 'Data controls' }).click()
  await expect(page.getByRole('heading', { name: 'Local activity history' })).toBeVisible()
  await page.getByText(/View \d+ recorded actions?/).click()
  await expect(page.getByText('Case created', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Request copied', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Pack viewed', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Pack approved', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Evidence added', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Submission edited', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Follow-up reminder exported', { exact: true }).first()).toBeVisible()
  const dataExportPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export ZIP' }).click()
  const dataExport = await dataExportPromise
  const dataArchive = await JSZip.loadAsync(await readFile((await dataExport.path())!))
  const dataManifest = JSON.parse(await dataArchive.file('case-record.json')!.async('string'))
  expect(dataManifest.case.consumerName).toBe('Synthetic Test Consumer')
  expect(dataManifest.auditLog.some((event: { action: string }) => event.action === 'case_exported')).toBe(true)
})

test('extracted candidates require explicit confirmation, correction, or rejection', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  await page.getByLabel('Original file').setInputFiles({
    name: 'extractable-order.txt',
    mimeType: 'text/plain',
    buffer: Buffer.from('Order no. SYN-2048 placed on 2026-08-01. Total RM 130.00.'),
  })
  await page.getByLabel('What kind of record?').selectOption('receipt')
  await page.getByLabel('Description').fill('Extractable synthetic order')
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByRole('heading', { name: 'Check every candidate.' })).toBeVisible()
  await expect(page.getByText('3', { exact: true }).first()).toBeVisible()
  const cards = page.locator('article.candidate')
  await cards.nth(0).getByLabel('Candidate value').fill('not an amount')
  await cards.nth(0).getByRole('button', { name: 'Confirm correction' }).click()
  await expect(page.getByRole('alert')).toContainText('Enter an amount')
  await expect(page.getByRole('button', { name: /Continue to Aduen Check/ })).toBeDisabled()
  await cards.nth(0).getByLabel('Candidate value').fill('125.50')
  await cards.nth(0).getByRole('button', { name: 'Confirm correction' }).click()
  await cards.nth(1).getByRole('button', { name: 'Confirm' }).click()
  await cards.nth(2).getByRole('button', { name: 'Reject' }).click()
  await expect(page.getByText('Confirmed as 125.50')).toBeVisible()
  await cards.nth(0).getByRole('button', { name: 'Review decision again' }).click()
  await expect(page.getByRole('button', { name: /Continue to Aduen Check/ })).toBeDisabled()
  await cards.nth(0).getByLabel('Candidate value').fill('125.00')
  await cards.nth(0).getByRole('button', { name: 'Confirm correction' }).click()
  await page.reload()
  await page.getByRole('button', { name: /Resume saved case/ }).click()
  await expect(page.getByText('Confirmed as 125.00')).toBeVisible()
  await cards.nth(0).getByText('Decision history', { exact: true }).click()
  await expect(cards.nth(0).locator('details')).toContainText('125.50')
  await expect(page.getByText('Rejected — not used as a fact')).toBeVisible()
  await page.getByRole('button', { name: /Continue to Aduen Check/ }).click()
  await expect(page.getByRole('heading', { name: 'Review the record.' })).toBeVisible()
  await page.getByRole('button', { name: 'Data controls' }).click()
  await expect(page.getByRole('heading', { name: 'Local activity history' })).toBeVisible()
  await page.getByText(/View \d+ recorded actions?/).click()
  await expect(page.getByText('Derived fact reviewed', { exact: true }).first()).toBeVisible()
})
