import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import JSZip from 'jszip'
import { jsPDF } from 'jspdf'

async function acceptBoundary(page: import('@playwright/test').Page) {
  await page.addInitScript(() => localStorage.clear())
  await page.goto('/')
  const begin = page.getByRole('button', { name: 'Begin safety check' })
  await expect(begin).toBeDisabled({ timeout: 10_000 })
  await page.getByLabel(/I understand Aduen's role/).check()
  await begin.click()
}

async function reachCaseDetails(page: import('@playwright/test').Page) {
  await acceptBoundary(page)
  await page.getByRole('button', { name: /No urgent issue/ }).click()
  await expect(page.getByRole('heading', { name: 'Describe the purchase.' })).toBeVisible()
}

async function fillCase(page: import('@playwright/test').Page, overrides: { purpose?: string; category?: string; consumerLocation?: string; amount?: string; refundAmount?: string; claimAmount?: string; claimAccruedDate?: string; contactHistory?: string; contactDate?: string } = {}) {
  await page.getByLabel('Your name or chosen case name').fill('Synthetic Test Consumer')
  await page.getByLabel('Your location').selectOption(overrides.consumerLocation ?? 'malaysia')
  await page.getByLabel('Seller or merchant').fill('Synthetic Store')
  await page.getByLabel('Seller location').selectOption('malaysia')
  await page.getByLabel('Purchase date').fill('2026-08-01')
  await page.getByLabel('Amount paid (MYR)').fill(overrides.amount ?? '125.50')
  if (overrides.claimAmount) await page.getByLabel('Estimated legal claim amount (MYR)').fill(overrides.claimAmount)
  if (overrides.claimAccruedDate) await page.getByLabel('Date the claim accrued').fill(overrides.claimAccruedDate)
  await page.getByLabel('Payment method').selectOption({ label: 'Card' })
  await page.getByLabel('Purchase purpose').selectOption(overrides.purpose ?? 'personal')
  await page.getByLabel('Purchase category').selectOption(overrides.category ?? 'general_goods')
  await page.getByLabel('What went wrong?').selectOption('non_delivery')
  await page.getByLabel('Primary remedy').selectOption('refund')
  await page.getByLabel('Refund amount (RM)').fill(overrides.refundAmount ?? '125.50')
  await page.getByLabel('Merchant contact').selectOption(overrides.contactHistory ?? 'none')
  if (overrides.contactDate) await page.getByLabel('Date of latest contact').fill(overrides.contactDate)
  await page.getByRole('button', { name: /Save case draft/ }).click()
}

async function addEvidence(page: import('@playwright/test').Page, type: string, name: string, description: string) {
  const originalFile = page.getByLabel('Original file')
  await originalFile.setInputFiles({ name, mimeType: 'text/plain', buffer: Buffer.from(`Synthetic ${description}. No real consumer information.`) })
  await expect.poll(() => originalFile.evaluate((input: HTMLInputElement) => input.files?.[0]?.name)).toBe(name)
  await page.getByLabel('What kind of record?').selectOption(type)
  await page.getByLabel('Event date').fill('2026-08-01')
  await page.getByLabel('Description').fill(description)
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await expect(page.getByText(name)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add evidence' })).toBeEnabled()
}

async function recordOperatorReview(page: import('@playwright/test').Page) {
  await page.getByLabel('Reviewer code').fill('SYNTH-OPERATOR-01')
  for (const label of [
    'Transaction identity and amount match the evidence',
    'Routing eligibility and uncertainty are reviewed',
    'Dates and deadline assumptions are checked',
    'Unsupported allegations and conclusions are removed',
    'Evidence selection and redaction are reviewed',
  ]) await page.getByLabel(label).check()
  await page.getByRole('button', { name: 'Record operator review' }).click()
  await expect(page.getByText('Operator review recorded', { exact: true })).toBeVisible()
}

test('uncertain scope prevents pack preparation even with complete evidence', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page, { category: 'other' })
  await page.getByRole('button', { name: /Add evidence/ }).click()
  await addEvidence(page, 'receipt', 'receipt.txt', 'order receipt')
  await addEvidence(page, 'payment', 'payment.txt', 'payment record')
  await addEvidence(page, 'listing', 'listing.txt', 'delivery promise')
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByText('0', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Manual scope review' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Manual review needed' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Prepare merchant request' })).toHaveCount(0)
})

test('an overdue route source pauses supported route preparation', async ({ page }) => {
  await page.clock.install({ time: new Date('2027-03-23T12:00:00Z') })
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  await addEvidence(page, 'receipt', 'stale-route-receipt.txt', 'receipt')
  await addEvidence(page, 'payment', 'stale-route-payment.txt', 'payment')
  await addEvidence(page, 'listing', 'stale-route-listing.txt', 'listing')
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByRole('heading', { name: 'Manual source review' })).toBeVisible()
  await expect(page.getByText('This route source review is overdue. Check current official guidance before taking the next step.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Manual review needed' })).toBeDisabled()
  await page.getByRole('button', { name: 'BM' }).click()
  await expect(page.getByRole('heading', { name: 'Semakan sumber manual' })).toBeVisible()
  await expect(page.getByText('Semakan sumber laluan ini sudah melebihi tempoh. Semak panduan rasmi semasa sebelum mengambil langkah seterusnya.')).toBeVisible()
  await expect(page.getByText('Semak sumber laluan semasa')).toBeVisible()
})

test('TTPM pre-check records claim amount and accrual date without claiming eligibility', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-24T12:00:00Z') })
  await reachCaseDetails(page)
  await fillCase(page, { claimAmount: '50000.01', claimAccruedDate: '2022-09-20', contactHistory: 'contacted', contactDate: '2026-09-20' })
  await page.getByRole('button', { name: /Add evidence/ }).click()
  await addEvidence(page, 'receipt', 'ttpm-receipt.txt', 'receipt')
  await addEvidence(page, 'payment', 'ttpm-payment.txt', 'payment record')
  await addEvidence(page, 'listing', 'ttpm-listing.txt', 'delivery promise')
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByRole('heading', { name: 'Manual route review' })).toBeVisible()
  await expect(page.getByText('above RM50,000')).toBeVisible()
  await expect(page.getByText('more than three years ago')).toBeVisible()
  await expect(page.getByText('TTPM claim amount and accrual date require official verification')).toBeVisible()
})

test('urgent risk blocks the ordinary intake path', async ({ page }) => {
  await acceptBoundary(page)
  await page.getByLabel('A payment or transaction was not authorised by me').check()
  await expect(page.getByRole('alert')).toContainText('Pause ordinary case preparation')
  await expect(page.getByRole('button', { name: /No urgent issue/ })).toHaveCount(0)
})

test('uploaded images can be previewed and closed locally', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  const pngBase64 = await page.evaluate(() => {
    const canvas = document.createElement('canvas')
    canvas.width = 20; canvas.height = 20
    const context = canvas.getContext('2d')!
    context.fillStyle = '#fff'
    context.fillRect(0, 0, 20, 20)
    return canvas.toDataURL('image/png').split(',')[1]
  })
  const originalPng = Buffer.from(pngBase64, 'base64')
  await page.getByLabel('Original file').setInputFiles({ name: 'synthetic-pixel.png', mimeType: 'image/png', buffer: originalPng })
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await page.getByLabel('I reviewed these warnings and still need to include this original.').check()
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await page.getByRole('button', { name: 'Preview image', exact: true }).click()
  const preview = page.getByRole('img', { name: 'synthetic-pixel.png' })
  await expect(preview).toBeVisible()
  await expect.poll(() => preview.evaluate((image: HTMLImageElement) => image.naturalWidth)).toBe(20)
  await expect(preview).toHaveAttribute('src', /^blob:/)
  await page.getByRole('button', { name: 'Prepare redacted image copy' }).click()
  await page.getByRole('button', { name: 'Add central redaction' }).click()
  const redactedDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download redacted image copy' }).click()
  const redactedFile = await redactedDownload
  expect(redactedFile.suggestedFilename()).toBe('redacted-synthetic-pixel.png')
  expect(Buffer.compare(await readFile((await redactedFile.path())!), originalPng)).not.toBe(0)
  await page.getByRole('button', { name: 'Clear redactions' }).click()
  await page.getByRole('button', { name: 'Add central redaction' }).focus()
  await page.keyboard.press('Enter')
  const keyboardRedactedDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download redacted image copy' }).focus()
  await page.keyboard.press('Enter')
  expect((await keyboardRedactedDownload).suggestedFilename()).toBe('redacted-synthetic-pixel.png')
  await page.getByRole('button', { name: 'Close image preview' }).click()
  await expect(preview).toHaveCount(0)
  const originalDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download original' }).click()
  const originalFile = await originalDownload
  expect(originalFile.suggestedFilename()).toBe('synthetic-pixel.png')
  expect(await readFile((await originalFile.path())!)).toEqual(originalPng)
})

test('image OCR stays on-device and produces unconfirmed review candidates', async ({ page }) => {
  test.setTimeout(120_000)
  const externalRequests: string[] = []
  page.on('request', (request) => {
    if (!request.url().startsWith('http://127.0.0.1:')) externalRequests.push(request.url())
  })
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  const pngBase64 = await page.evaluate(() => {
    const canvas = document.createElement('canvas')
    canvas.width = 1200; canvas.height = 360
    const context = canvas.getContext('2d')!
    context.fillStyle = '#fff'; context.fillRect(0, 0, canvas.width, canvas.height)
    context.fillStyle = '#000'; context.font = 'bold 84px Arial'; context.fillText('Total RM 130.00', 30, 160)
    context.font = 'bold 96px Arial'; context.fillText('OTP 123456', 30, 315)
    return canvas.toDataURL('image/png').split(',')[1]
  })
  await page.getByLabel('Original file').setInputFiles({ name: 'synthetic-receipt.png', mimeType: 'image/png', buffer: Buffer.from(pngBase64, 'base64') })
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await expect(page.getByRole('alert')).toContainText('Local OCR checked')
  await expect(page.getByRole('alert')).toContainText('password, PIN, OTP')
  await page.getByLabel('I reviewed these warnings and still need to include this original.').check()
  await page.getByRole('button', { name: 'Add evidence' }).click({ timeout: 120_000 })
  await expect(page.getByText('synthetic-receipt.png', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByRole('heading', { name: 'Check every candidate.' })).toBeVisible()
  const amountCandidate = page.locator('article.candidate').filter({ hasText: '130.00' })
  await expect(amountCandidate).toContainText('ocr-local-v3')
  await expect(amountCandidate.getByRole('button', { name: 'Confirm' })).toBeEnabled()
  expect(externalRequests).toEqual([])
})

test('image OCR failure preserves the original for manual review', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(window, 'Worker', {
    configurable: true,
    value: class { constructor() { throw new Error('Synthetic OCR worker failure.') } },
  }))
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  const pngBase64 = await page.evaluate(() => {
    const canvas = document.createElement('canvas')
    canvas.width = 20; canvas.height = 20
    const context = canvas.getContext('2d')!
    context.fillStyle = '#fff'; context.fillRect(0, 0, canvas.width, canvas.height)
    return canvas.toDataURL('image/png').split(',')[1]
  })
  await page.getByLabel('Original file').setInputFiles({ name: 'synthetic-ocr-failure.png', mimeType: 'image/png', buffer: Buffer.from(pngBase64, 'base64') })
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await expect(page.getByRole('alert')).toContainText('was not scanned for sensitive content')
  await page.getByLabel('I reviewed these warnings and still need to include this original.').check()
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await expect(page.getByText('synthetic-ocr-failure.png', { exact: true })).toBeVisible()
})

test('scanned PDF OCR creates review candidates without changing the original', async ({ page }) => {
  test.setTimeout(120_000)
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  const image = await page.evaluate(() => {
    const canvas = document.createElement('canvas')
    canvas.width = 1200; canvas.height = 360
    const context = canvas.getContext('2d')!
    context.fillStyle = '#fff'; context.fillRect(0, 0, canvas.width, canvas.height)
    context.fillStyle = '#000'; context.font = 'bold 84px Arial'; context.fillText('Total RM 130.00', 30, 160)
    context.font = 'bold 96px Arial'; context.fillText('OTP 123456', 30, 315)
    return canvas.toDataURL('image/png')
  })
  const pdf = new jsPDF()
  pdf.addImage(image, 'PNG', 10, 30, 190, 45)
  const original = Buffer.from(pdf.output('arraybuffer'))
  await page.getByLabel('Original file').setInputFiles({ name: 'synthetic-scanned-receipt.pdf', mimeType: 'application/pdf', buffer: original })
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await expect(page.getByRole('alert')).toContainText('Local OCR checked')
  await expect(page.getByRole('alert')).toContainText('password, PIN, OTP')
  await page.getByLabel('I reviewed these warnings and still need to include this original.').check()
  await page.getByRole('button', { name: 'Add evidence' }).click({ timeout: 120_000 })
  await expect(page.getByText('synthetic-scanned-receipt.pdf', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByRole('heading', { name: 'Check every candidate.' })).toBeVisible()
  const amountCandidate = page.locator('article.candidate').filter({ hasText: '130.00' })
  await expect(amountCandidate).toContainText('ocr-local-v3')
  await expect(amountCandidate.getByRole('button', { name: 'Confirm' })).toBeEnabled()
  await page.getByRole('button', { name: 'Data controls' }).click()
  const archiveDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export ZIP' }).click()
  const archiveFile = await archiveDownload
  const archive = await JSZip.loadAsync(await readFile((await archiveFile.path())!))
  expect(await archive.file('evidence-originals/01-synthetic-scanned-receipt.pdf')!.async('nodebuffer')).toEqual(original)
})

test('hybrid PDFs OCR image-bearing pages alongside searchable text', async ({ page }) => {
  test.setTimeout(120_000)
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  const image = await page.evaluate(() => {
    const canvas = document.createElement('canvas')
    canvas.width = 1200; canvas.height = 260
    const context = canvas.getContext('2d')!
    context.fillStyle = '#fff'; context.fillRect(0, 0, canvas.width, canvas.height)
    context.fillStyle = '#000'; context.font = 'bold 84px Arial'; context.fillText('Total RM 130.00', 30, 160)
    return canvas.toDataURL('image/png')
  })
  const pdf = new jsPDF()
  pdf.text('Order no. SYN-HYBRID-2048.', 10, 15)
  pdf.addImage(image, 'PNG', 10, 30, 190, 45)
  await page.getByLabel('Original file').setInputFiles({ name: 'synthetic-hybrid-receipt.pdf', mimeType: 'application/pdf', buffer: Buffer.from(pdf.output('arraybuffer')) })
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await expect(page.getByRole('alert')).toContainText('Local OCR checked image-bearing pages')
  await page.getByLabel('I reviewed these warnings and still need to include this original.').check()
  await page.getByRole('button', { name: 'Add evidence' }).click({ timeout: 120_000 })
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByRole('heading', { name: 'Check every candidate.' })).toBeVisible()
  const candidates = page.locator('article.candidate')
  await expect(candidates).toHaveCount(2)
  const amountCandidate = candidates.nth(0)
  await expect(amountCandidate).toContainText('ocr-local-v3')
  const referenceCandidate = candidates.nth(1)
  await expect(referenceCandidate).toContainText('SYN-HYBRID-2048')
  await expect(referenceCandidate).toContainText('ocr-local-v3')
})

test('rejects oversized evidence before content scanning', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  await page.getByLabel('Original file').setInputFiles({ name: 'oversized.txt', mimeType: 'text/plain', buffer: Buffer.alloc(10 * 1024 * 1024 + 1, 65) })
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await expect(page.getByRole('alert')).toContainText('larger than the 10 MB prototype limit')
  await expect(page.locator('.risk-review')).toHaveCount(0)
})

test('uploaded PDFs can be redacted locally into a flattened copy without changing the original', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  const fixture = new jsPDF({ unit: 'pt', format: [600, 800] })
  fixture.setFontSize(24)
  fixture.text('SYNTHETIC PRIVATE DETAILS', 90, 130)
  const originalBytes = Buffer.from(fixture.output('arraybuffer'))
  await page.getByLabel('Original file').setInputFiles({ name: 'synthetic-receipt.pdf', mimeType: 'application/pdf', buffer: originalBytes })
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await page.getByLabel('I reviewed these warnings and still need to include this original.').check()
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await page.getByRole('button', { name: 'Preview and redact PDF', exact: true }).click()
  const exportButton = page.getByRole('button', { name: 'Download flattened redacted PDF' })
  await expect(exportButton).toBeDisabled()
  const pdfPage = page.locator('section[aria-label="Page 1"]')
  await expect(pdfPage.locator('canvas')).toBeVisible()
  await expect(page.getByRole('status', { name: 'Rendering PDF pages…' })).toHaveCount(0)
  await expect(exportButton).toBeDisabled()
  await pdfPage.locator('canvas').evaluate((canvas) => window.scrollBy(0, canvas.getBoundingClientRect().top - 100))
  const canvasBox = await pdfPage.locator('canvas').boundingBox()
  expect(canvasBox).not.toBeNull()
  await page.mouse.move(canvasBox!.x + canvasBox!.width * 0.12, canvasBox!.y + canvasBox!.height * 0.11)
  await page.mouse.down()
  await page.mouse.move(canvasBox!.x + canvasBox!.width * 0.65, canvasBox!.y + canvasBox!.height * 0.17)
  await page.mouse.up()
  await expect(exportButton).toBeEnabled()
  const redactedDownload = page.waitForEvent('download')
  await exportButton.click()
  const redactedFile = await redactedDownload
  expect(redactedFile.suggestedFilename()).toMatch(/^redacted-evidence-.+\.pdf$/)
  const redactedBytes = await readFile((await redactedFile.path())!)
  expect(redactedBytes.subarray(0, 5).toString()).toBe('%PDF-')
  expect(redactedBytes.includes(Buffer.from('SYNTHETIC PRIVATE DETAILS'))).toBe(false)

  const originalDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download original' }).click()
  const original = await originalDownload
  expect(await readFile((await original.path())!)).toEqual(originalBytes)

  const centralRedaction = pdfPage.getByRole('button', { name: 'Add central redaction · 1' })
  await centralRedaction.focus()
  await page.keyboard.press('Enter')
  await expect(pdfPage.getByRole('status')).toHaveText('2 redactions applied to page 1.')
  const clearRedactions = pdfPage.getByRole('button', { name: 'Clear redactions · 1' })
  await clearRedactions.focus()
  await page.keyboard.press('Enter')
  await expect(pdfPage.getByRole('status')).toHaveText('No redactions on page 1.')
  await centralRedaction.focus()
  await page.keyboard.press('Enter')
  await expect(pdfPage.getByRole('status')).toHaveText('1 redaction applied to page 1.')
  const keyboardDownload = page.waitForEvent('download')
  await exportButton.focus()
  await page.keyboard.press('Enter')
  expect((await keyboardDownload).suggestedFilename()).toMatch(/^redacted-evidence-.+\.pdf$/)
})

test('draft deletion can be cancelled and confirmed deletion removes saved case data', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  page.once('dialog', (dialog) => dialog.dismiss())
  await page.getByRole('button', { name: 'Delete draft', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Delete draft', exact: true })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('Aduen.case-record.v1'))).not.toBeNull()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete draft', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Begin safety check' })).toBeDisabled()
  expect(await page.evaluate(() => localStorage.getItem('Aduen.case-record.v1'))).toBeNull()
  expect(await page.evaluate(() => localStorage.getItem('Aduen.audit-log.v1'))).toBeNull()
  await page.reload()
  await expect(page.getByRole('button', { name: /Resume saved case/ })).toHaveCount(0)
})

test('deletion reports failure when the browser cannot remove the local audit log', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.evaluate(() => {
    const removeItem = Storage.prototype.removeItem
    Storage.prototype.removeItem = function (key: string) {
      if (key === 'Aduen.audit-log.v1') throw new DOMException('Storage is blocked', 'SecurityError')
      return removeItem.call(this, key)
    }
  })
  await page.getByRole('button', { name: 'Data controls' }).click()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete all case data' }).click()
  await expect(page.getByRole('alert')).toContainText('Deletion did not complete')
  expect(await page.evaluate(() => localStorage.getItem('Aduen.case-record.v1'))).not.toBeNull()
})

test('an unsupported sector stops before evidence collection', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page, { category: 'healthcare' })
  await expect(page.getByRole('heading', { name: 'Aduen should not prepare this case.' })).toBeVisible()
  await expect(page.getByText('Healthcare matters are excluded')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add evidence' })).toHaveCount(0)
})

test('published TTPM exclusions have explicit intake categories and stop case preparation', async ({ page }) => {
  await reachCaseDetails(page)
  const exclusions = [
    ['personal_injury', 'Claims arising from personal injury or death are excluded from TTPM jurisdiction.'],
    ['wills_estates', 'Wills, inheritance, and estate-rights disputes are excluded from TTPM jurisdiction.'],
    ['franchise', 'Franchise disputes are excluded from TTPM jurisdiction.'],
    ['goodwill_ip', 'Goodwill, trade-secret, and intellectual-property disputes are excluded from TTPM jurisdiction.'],
    ['other_tribunal', 'This subject may belong to another tribunal and is outside the prototype’s supported scope.'],
  ] as const
  await fillCase(page, { category: exclusions[0][0] })
  for (const [index, [category, reason]] of exclusions.entries()) {
    if (index > 0) {
      await page.getByRole('button', { name: 'Review case details' }).click()
      await page.getByLabel('Purchase category').selectOption(category)
      await page.getByRole('button', { name: /Save case draft/ }).click()
    }
    await expect(page.getByRole('heading', { name: 'Aduen should not prepare this case.' })).toBeVisible()
    await expect(page.getByText(reason, { exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Add evidence' })).toHaveCount(0)
  }
})

test('aviation cases receive the current CAAM handoff before evidence collection', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page, { category: 'aviation' })
  await expect(page.getByRole('heading', { name: 'Aduen should not prepare this case.' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Open CAAM/FlySmart complaint guidance' })).toHaveAttribute('href', 'https://www.caam.gov.my/consumer/complaints/make-a-complaint/')
  await expect(page.getByText('Contact the airline, airport, or provider first.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add evidence' })).toHaveCount(0)
})

test('financial-service cases receive the provider-first BNM handoff before evidence collection', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page, { category: 'financial_service' })
  await expect(page.getByRole('link', { name: 'Open Bank Negara Malaysia complaint process' })).toHaveAttribute('href', 'https://www.bnm.gov.my/contact-us/lodge-complaint')
  await expect(page.getByText('Complain to the financial service provider’s Complaints Unit first.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add evidence' })).toHaveCount(0)
})

test('overdue sector sources hide time-dependent instructions but keep official source links', async ({ page }) => {
  await page.clock.install({ time: new Date('2027-03-23T12:00:00Z') })
  await reachCaseDetails(page)
  for (const [index, category, linkName] of [
    [0, 'aviation', 'Open official CAAM source'],
    [1, 'financial_service', 'Open official Bank Negara Malaysia source'],
  ] as const) {
    if (index > 0) {
      await page.getByRole('button', { name: 'Review case details' }).click()
      await page.getByLabel('Purchase category').selectOption(category)
      await page.getByRole('button', { name: /Save case draft/ }).click()
    } else {
      await fillCase(page, { category })
    }
    await expect(page.getByRole('link', { name: linkName })).toBeVisible()
    const sourceNote = page.locator('.source-note')
    await expect(sourceNote).toContainText('over 180 days old')
    await expect(sourceNote).not.toContainText(/14 days|30 days/)
  }
})

test('a supported draft preserves original evidence and resumes at the evidence stage', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  await page.getByLabel('Original file').setInputFiles({ name: 'synthetic-receipt.txt', mimeType: 'text/plain', buffer: Buffer.from("Synthetic order receipt. Total MYR 125.50. This contains someone else's phone number. <script>window.evidenceExecuted=true</script>") })
  await page.getByLabel('Event date').fill('2026-08-01')
  await page.getByLabel('Description').fill('Synthetic order receipt')
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await expect(page.getByRole('alert')).toContainText('appears to mention another person')
  await page.getByLabel('I reviewed these warnings and still need to include this original.').check()
  await page.getByRole('button', { name: 'Add evidence' }).click()
  const inclusion = page.getByLabel('Include in pack')
  await inclusion.click()
  await expect(inclusion).not.toBeChecked()
  await inclusion.click()
  await expect(inclusion).toBeChecked()
  await expect(page.getByText('synthetic-receipt.txt')).toBeVisible()
  await page.getByRole('button', { name: 'Preview text', exact: true }).click()
  await expect(page.getByLabel('Evidence contents')).toContainText('<script>window.evidenceExecuted=true</script>')
  expect(await page.evaluate(() => 'evidenceExecuted' in window)).toBe(false)
  await page.getByRole('button', { name: 'Prepare redacted copy' }).click()
  const redactedCopy = page.getByLabel('Redacted copy contents')
  await expect(redactedCopy).toBeVisible()
  await redactedCopy.fill('Synthetic order receipt. [redacted]')
  const redactedDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download redacted copy' }).click()
  const redactedFile = await redactedDownload
  expect(redactedFile.suggestedFilename()).toMatch(/^redacted-evidence-.+\.txt$/)
  const redactedContent = await readFile((await redactedFile.path())!, 'utf8')
  expect(redactedContent).toContain('[redacted]')
  expect(redactedContent).not.toContain('window.evidenceExecuted')
  await page.getByRole('button', { name: 'Close redacted copy' }).click()
  await page.getByRole('button', { name: 'Close text preview' }).click()
  await expect(page.getByLabel('Evidence contents')).toHaveCount(0)
  const originalDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download original' }).click()
  const originalFile = await originalDownload
  expect(originalFile.suggestedFilename()).toBe('synthetic-receipt.txt')
  expect(await readFile((await originalFile.path())!, 'utf8')).toContain('window.evidenceExecuted')
  await page.reload()
  await page.getByRole('button', { name: /Resume saved case/ }).click()
  await expect(page.getByRole('heading', { name: 'Keep the originals.' })).toBeVisible()
  await expect(page.getByText('synthetic-receipt.txt')).toBeVisible()
  await page.getByRole('button', { name: 'Data controls' }).click()
  await expect(page.getByRole('heading', { name: 'Local activity history' })).toBeVisible()
  await page.getByText(/View \d+ recorded actions?/).click()
  await expect(page.getByText('Case edited', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Evidence inclusion changed', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Evidence previewed')).toBeVisible()
})

test('a corrupted case autosave restores the previous version and reports the recovery', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: 'Edit details' }).click()
  await page.getByLabel('Seller or merchant').fill('Synthetic newer seller')
  await page.evaluate(() => localStorage.setItem('Aduen.case-record.v1', '{broken json'))
  await page.reload()
  await expect(page.getByRole('status').filter({ hasText: 'A previous case autosave was restored' })).toBeVisible()
  await page.getByRole('button', { name: 'BM', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Simpanan kes terdahulu dipulihkan' })).toBeVisible()
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await page.getByRole('button', { name: /Resume saved case/ }).click()
  await expect(page.getByRole('heading', { name: 'Keep the originals.' })).toBeVisible()
  await page.getByRole('button', { name: '← Case details' }).click()
  await expect(page.getByLabel('Seller or merchant')).toHaveValue('Synthetic Store')
  await page.getByRole('button', { name: 'Data controls' }).click()
  await page.getByText(/View \d+ recorded actions?/).click()
  await expect(page.getByText('Previous case autosave restored', { exact: true })).toBeVisible()
})

test('a complete merchant-first case reaches approved PDF export and outcome tracking', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => undefined } }))
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  await addEvidence(page, 'receipt', 'receipt.txt', 'order receipt')
  await addEvidence(page, 'payment', 'payment.txt', 'payment record')
  await addEvidence(page, 'listing', 'listing.txt', 'promised delivery listing')
  await addEvidence(page, 'message', 'message.txt', 'written merchant request')
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByText('0', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Merchant or platform first' })).toBeVisible()
  const reviewBriefDownloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export manual review brief' }).click()
  const reviewBriefDownload = await reviewBriefDownloadPromise
  const reviewBrief = JSON.parse(await readFile((await reviewBriefDownload.path())!, 'utf8'))
  expect(reviewBrief.route.confidence).toBe('supported')
  expect(reviewBrief.evidence).toHaveLength(4)
  expect(reviewBrief).not.toHaveProperty('originals')
  await page.getByRole('button', { name: 'Prepare merchant request' }).click()
  await expect(page.getByText('Aduen CASE PACK')).toBeVisible()
  await page.getByLabel(/I reviewed this pack/).check()
  await expect(page.getByRole('button', { name: /Approve and export PDF/ })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Export PDF and selected evidence (ZIP)' })).toBeDisabled()
  await recordOperatorReview(page)
  await expect(page.getByRole('button', { name: 'Export PDF and selected evidence (ZIP)' })).toBeDisabled()
  await page.getByLabel(/I reviewed this pack/).check()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: /Approve and export PDF/ }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('Aduen-synthetic-store-v1.pdf')
  await page.getByRole('button', { name: 'Copy approved request' }).click()
  await expect(page.getByRole('button', { name: 'Request copied' })).toBeVisible()
  const archivePromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export PDF and selected evidence (ZIP)' }).click()
  const archiveDownload = await archivePromise
  expect(archiveDownload.suggestedFilename()).toBe('Aduen-synthetic-store-v1-handoff.zip')
  const archive = await JSZip.loadAsync(await readFile((await archiveDownload.path())!))
  const manifest = JSON.parse(await archive.file('manifest.json')!.async('string'))
  expect(manifest.evidence).toHaveLength(4)
  for (const entry of manifest.evidence) {
    expect(await archive.file(entry.archivePath)!.async('string')).toContain('Synthetic')
  }
  expect(manifest.pack.operatorReview.reviewerCode).toBe('SYNTH-OPERATOR-01')
  expect(await archive.file('Aduen-synthetic-store-v1.pdf')!.async('string')).toMatch(/^%PDF/)
  await page.getByRole('button', { name: /Track external status/ }).click()
  await page.getByLabel('Recipient or channel').fill('Synthetic merchant email')
  await page.getByLabel('Submission date').fill('2026-08-10')
  await page.getByLabel('External reference').fill('SYNTH-001')
  await page.getByLabel('Next follow-up').fill('2026-08-17')
  await page.getByLabel('Response summary').fill('Synthetic merchant acknowledged the request.')
  await page.getByRole('button', { name: /Save status/ }).click()
  await expect(page.getByRole('status')).toContainText('Status saved')
  await expect(page.getByText('Awaiting response', { exact: true })).toBeVisible()
  await expect(page.getByText('This reminder is based on the follow-up date you entered, not an external deadline.')).toBeVisible()
  const calendarDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download calendar reminder' }).click()
  expect((await calendarDownload).suggestedFilename()).toBe('Aduen-follow-up-2026-08-17.ics')
  await page.reload()
  await page.getByRole('button', { name: /Resume saved case/ }).click()
  await expect(page.getByLabel('External reference')).toHaveValue('SYNTH-001')
  await page.getByRole('button', { name: '← Pack', exact: true }).click()
  await expect(page.getByText('Aduen CASE PACK')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Export PDF and selected evidence (ZIP)' })).toBeEnabled()
  await page.getByRole('button', { name: '← Aduen Check', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Review the record.' })).toBeVisible()
  await expect(page.getByText('0', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Prepare merchant request' })).toBeEnabled()
  await page.getByRole('button', { name: 'Data controls' }).click()
  await expect(page.getByRole('heading', { name: 'Local activity history' })).toBeVisible()
  await page.getByText(/View \d+ recorded actions?/).click()
  await expect(page.getByText('Case created', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Request copied', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Pack viewed', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Pack approved', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Evidence added', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Submission edited', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Follow-up reminder exported', { exact: true }).first()).toBeVisible()
  const dataExportPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export ZIP' }).click()
  const dataExport = await dataExportPromise
  const dataArchive = await JSZip.loadAsync(await readFile((await dataExport.path())!))
  const dataManifest = JSON.parse(await dataArchive.file('case-record.json')!.async('string'))
  expect(dataManifest.case.consumerName).toBe('Synthetic Test Consumer')
  expect(dataManifest.caseRecoveryBackup.draft.seller).toBe('Synthetic Store')
  expect(dataManifest.auditLog.some((event: { action: string }) => event.action === 'case_exported')).toBe(true)
})

test('extracted candidates require explicit confirmation, correction, or rejection', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  await page.getByLabel('Original file').setInputFiles({
    name: 'extractable-order.txt',
    mimeType: 'text/plain',
    buffer: Buffer.from('Order no. SYN-2048 placed on 2026-08-01. Total RM 130.00.'),
  })
  await page.getByLabel('What kind of record?').selectOption('receipt')
  await page.getByLabel('Description').fill('Extractable synthetic order')
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByRole('heading', { name: 'Check every candidate.' })).toBeVisible()
  await expect(page.getByText('3', { exact: true }).first()).toBeVisible()
  const cards = page.locator('article.candidate')
  await cards.nth(0).getByLabel('Candidate value').fill('not an amount')
  await cards.nth(0).getByRole('button', { name: 'Confirm correction' }).click()
  await expect(page.getByRole('alert')).toContainText('Enter an amount')
  await expect(page.getByRole('button', { name: /Continue to Aduen Check/ })).toBeDisabled()
  await cards.nth(0).getByLabel('Candidate value').fill('125.50')
  await cards.nth(0).getByRole('button', { name: 'Confirm correction' }).click()
  await cards.nth(1).getByRole('button', { name: 'Confirm' }).click()
  await cards.nth(2).getByRole('button', { name: 'Reject' }).click()
  await expect(page.getByText('Confirmed as 125.50')).toBeVisible()
  await cards.nth(0).getByRole('button', { name: 'Review decision again' }).click()
  await expect(page.getByRole('button', { name: /Continue to Aduen Check/ })).toBeDisabled()
  await cards.nth(0).getByLabel('Candidate value').fill('125.00')
  await cards.nth(0).getByRole('button', { name: 'Confirm correction' }).click()
  await expect(page.getByText('Confirmed as 125.00')).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: /Resume saved case/ }).click()
  await expect(page.getByRole('heading', { name: 'Check every candidate.' })).toBeVisible()
  await expect(page.getByText('Confirmed as 125.00')).toBeVisible()
  await cards.nth(0).getByText('Decision history', { exact: true }).click()
  await expect(cards.nth(0).locator('details')).toContainText('125.50')
  await expect(page.getByText('Rejected - not used as a fact')).toBeVisible()
  await page.getByRole('button', { name: /Continue to Aduen Check/ }).click()
  await expect(page.getByRole('heading', { name: 'Review the record.' })).toBeVisible()
  await page.getByRole('button', { name: 'Data controls' }).click()
  await expect(page.getByRole('heading', { name: 'Local activity history' })).toBeVisible()
  await page.getByText(/View \d+ recorded actions?/).click()
  await expect(page.getByText('Derived fact reviewed', { exact: true }).first()).toBeVisible()
})

test('searchable PDF text creates reviewable candidates without changing the original', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  const pdf = new jsPDF()
  pdf.text(['Order no. SYN-PDF-2048. Order date: 2026-08-01. Total RM 130.00.', 'Contact: synthetic@example.test.'], 20, 20)
  const original = Buffer.from(pdf.output('arraybuffer'))
  await page.getByLabel('Original file').setInputFiles({ name: 'searchable-order.pdf', mimeType: 'application/pdf', buffer: original })
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await expect(page.getByRole('alert')).toContainText('email address or Malaysian mobile number')
  await expect(page.getByRole('alert')).toContainText('up to 500,000 characters across 30 pages')
  await page.getByLabel('I reviewed these warnings and still need to include this original.').check()
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByRole('heading', { name: 'Check every candidate.' })).toBeVisible()
  await expect(page.getByText('pdf-text-v3', { exact: true })).toBeVisible()
  const cards = page.locator('article.candidate')
  await expect(cards).toHaveCount(3)
  await expect(cards.nth(0)).toContainText('130.00')
  await expect(cards.nth(0).getByRole('button', { name: 'Confirm' })).toBeEnabled()
  await page.getByRole('button', { name: 'Data controls' }).click()
  const archiveDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export ZIP' }).click()
  const downloadedArchive = await archiveDownload
  const archive = await JSZip.loadAsync(await readFile((await downloadedArchive.path())!))
  const manifest = JSON.parse(await archive.file('case-record.json')!.async('string'))
  expect(manifest.extractions[0].extractorVersion).toBe('pdf-text-v3')
  expect(await archive.file('evidence-originals/01-searchable-order.pdf')!.async('nodebuffer')).toEqual(original)
})

test('confirmed amounts that disagree across evidence block request preparation', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  for (const [name, amount] of [['receipt-one.txt', '130.00'], ['receipt-two.txt', '125.50']]) {
    await page.getByLabel('Original file').setInputFiles({ name, mimeType: 'text/plain', buffer: Buffer.from(`Total RM ${amount}. Synthetic evidence.`) })
    await page.getByLabel('What kind of record?').selectOption('receipt')
    await page.getByLabel('Description').fill(`Synthetic receipt ${amount}`)
    await page.getByRole('button', { name: 'Add evidence' }).click()
    await expect(page.getByText(name, { exact: true })).toBeVisible()
  }
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByRole('heading', { name: 'Check every candidate.' })).toBeVisible()
  const confirmButtons = page.getByRole('button', { name: 'Confirm', exact: true })
  await expect(confirmButtons).toHaveCount(2)
  await confirmButtons.nth(0).click()
  await confirmButtons.nth(1).click()
  await page.getByRole('button', { name: /Continue to Aduen Check/ }).click()
  await expect(page.getByRole('heading', { name: 'Review the record.' })).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('Confirmed evidence contains different transaction amounts.')
  await expect(page.getByRole('button', { name: 'Resolve fact conflicts' })).toBeDisabled()
})

test('a refund above the transaction amount requires clarification', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page, { amount: '100.00', refundAmount: '125.00' })
  await page.getByRole('button', { name: /Add evidence/ }).click()
  await addEvidence(page, 'receipt', 'oversized-refund-receipt.txt', 'receipt')
  await addEvidence(page, 'payment', 'oversized-refund-payment.txt', 'payment record')
  await addEvidence(page, 'listing', 'oversized-refund-listing.txt', 'delivery promise')
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByRole('heading', { name: 'Review the record.' })).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('The requested refund amount is greater than the recorded transaction amount.')
  await expect(page.getByRole('button', { name: 'Resolve fact conflicts' })).toBeDisabled()
})

test('an invoice number does not conflict with a separate order number', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  for (const [name, reference] of [['order.txt', 'Order no. ADU-1234'], ['invoice.txt', 'Invoice no. INV-5678']]) {
    await page.getByLabel('Original file').setInputFiles({ name, mimeType: 'text/plain', buffer: Buffer.from(`${reference}. Synthetic evidence.`) })
    await page.getByLabel('What kind of record?').selectOption('receipt')
    await page.getByLabel('Description').fill(`Synthetic ${name}`)
    await page.getByRole('button', { name: 'Add evidence' }).click()
    await expect(page.getByText(name, { exact: true })).toBeVisible()
  }
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByRole('heading', { name: 'Check every candidate.' })).toBeVisible()
  const confirmButtons = page.getByRole('button', { name: 'Confirm', exact: true })
  await expect(confirmButtons).toHaveCount(2)
  await confirmButtons.nth(0).click()
  await confirmButtons.nth(1).click()
  await page.getByRole('button', { name: /Continue to Aduen Check/ }).click()
  await expect(page.getByRole('heading', { name: 'Review the record.' })).toBeVisible()
  await expect(page.locator('.conflict-panel')).toHaveCount(0)
})

test('confirmed purchase and delivery dates in reverse order block request preparation', async ({ page }) => {
  await reachCaseDetails(page)
  await fillCase(page)
  await page.getByRole('button', { name: /Add evidence/ }).click()
  await page.getByLabel('Original file').setInputFiles({
    name: 'synthetic-order-dates.txt',
    mimeType: 'text/plain',
    buffer: Buffer.from('Purchase date: 2026-08-05. Delivery date: 2026-08-02. Synthetic example.'),
  })
  await page.getByLabel('What kind of record?').selectOption('receipt')
  await page.getByLabel('Description').fill('Synthetic order and delivery dates')
  await page.getByRole('button', { name: 'Add evidence' }).click()
  await page.getByRole('button', { name: /Review case/ }).click()
  await expect(page.getByRole('heading', { name: 'Check every candidate.' })).toBeVisible()
  const confirmButtons = page.getByRole('button', { name: 'Confirm', exact: true })
  await expect(confirmButtons).toHaveCount(2)
  await confirmButtons.nth(0).click()
  await confirmButtons.nth(1).click()
  await page.getByRole('button', { name: /Continue to Aduen Check/ }).click()
  await expect(page.getByRole('heading', { name: 'Review the record.' })).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('A confirmed delivery date occurs before the recorded purchase date.')
  await expect(page.getByText('Purchase date in evidence')).toBeVisible()
  await expect(page.getByText('Delivery date in evidence')).toBeVisible()
  await expect(page.getByText('confirmed extracted fact', { exact: true })).toHaveCount(2)
  await expect(page.getByRole('button', { name: 'Resolve fact conflicts' })).toBeDisabled()
})
