version: 2
updates:
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
    groups:
      app-dependencies:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /service/api
    schedule:
      interval: weekly
    groups:
      api-dependencies:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /service/api
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
